FROM mcr.microsoft.com/mssql/server:{TAG}
USER root
ADD nodirect_open.c /
RUN apt update && \
    apt install -y gcc && \
    gcc -shared -fpic -o /nodirect_open.so nodirect_open.c -ldl && \
    apt purge -y gcc && \
    apt clean && \
    echo "/nodirect_open.so" >> /etc/ld.so.preload