name: docker-push

on:
  push:
    tags:
      - "*"

jobs:
  docker-push:
    name: docker-push
    runs-on: ubuntu-latest
    env:
      DockerRegistryUsername: ${{ secrets.DOCKERREGISTRYUSERNAME }}
      DockerRegistryPassword: ${{ secrets.DOCKERREGISTRYPASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - name: Run './build.sh PushDocker'
        run: ./build.sh PushDocker
